# =============================================
# Clock Constraint Definitions
# =============================================

# Create primary system clock constraint
# - Clock name: sys_clk_300
# - Period: 3.333 ns (300 MHz frequency)
# - Applied to: sys_clk_300Mhz_p port (differential clock positive pin)
# This is the main system clock for the FPGA logic
create_clock -name sys_clk_300 -period 3.333 [get_ports sys_clk_300Mhz_p]

# Create GT reference clock constraint for transceivers
# - Clock name: gt_refclk_in_p  
# - Period: 6.4 ns (156.25 MHz frequency)
# - Applied to: gt_refclk_in_p port
# This clock is used as reference for Gigabit Transceivers (GTs)
# Typical frequencies: 156.25 MHz for 10G Ethernet, 125 MHz for 1G Ethernet
create_clock -name gt_refclk_in_p -period 6.4 [get_ports gt_refclk_in_p]

# Create receive path clock constraint
# - Clock name: rx_axis_aclk
# - Period: 6.4 ns (156.25 MHz frequency)
# - Waveform: 0.000 to 3.200 ns (50% duty cycle)
# - Applied to: hierarchical pin u_udp_stack_top/rx_clk_out_0
# This is the receive clock generated by the Ethernet IP core
# Used for AXI-Stream interface in receive direction
create_clock -period 6.400 -name rx_axis_aclk -waveform {0.000 3.200} [get_pins -hierarchical "u_udp_stack_top/rx_clk_out_0"]

# Create transmit path clock constraint
# - Clock name: tx_axis_aclk
# - Period: 6.4 ns (156.25 MHz frequency) 
# - Waveform: 0.000 to 3.200 ns (50% duty cycle)
# - Applied to: hierarchical pin u_udp_stack_top/tx_clk_out_0
# This is the transmit clock generated by the Ethernet IP core
# Used for AXI-Stream interface in transmit direction
create_clock -period 6.400 -name tx_axis_aclk -waveform {0.000 3.200} [get_pins -hierarchical "u_udp_stack_top/tx_clk_out_0"]




