# =============================================
# Clock Constraint Definitions
# =============================================

# Create primary system clock constraint
# - Clock name: sys_clk_300
# - Period: 3.333 ns (300 MHz frequency)
# - Applied to: sys_clk_300Mhz_p port (differential clock positive pin)
# This is the main system clock for the FPGA logic
create_clock -period 3.333 -name sys_clk_300 [get_ports sys_clk_300Mhz_p]

# Create GT reference clock constraint for transceivers
# - Clock name: gt_refclk_in_p
# - Period: 6.4 ns (156.25 MHz frequency)
# - Applied to: gt_refclk_in_p port
# This clock is used as reference for Gigabit Transceivers (GTs)
# Typical frequencies: 156.25 MHz for 10G Ethernet, 125 MHz for 1G Ethernet
create_clock -period 6.400 -name gt_refclk_in_p [get_ports gt_refclk_in_p]

# Create receive path clock constraint
# - Clock name: rx_axis_aclk
# - Period: 6.4 ns (156.25 MHz frequency)
# - Waveform: 0.000 to 3.200 ns (50% duty cycle)
# - Applied to: hierarchical pin u_udp_stack_top/rx_clk_out_0
# This is the receive clock generated by the Ethernet IP core
# Used for AXI-Stream interface in receive direction
create_clock -period 6.400 -name rx_axis_aclk -waveform {0.000 3.200} [get_pins -hierarchical u_udp_stack_top/rx_clk_out_0]

# Create transmit path clock constraint
# - Clock name: tx_axis_aclk
# - Period: 6.4 ns (156.25 MHz frequency)
# - Waveform: 0.000 to 3.200 ns (50% duty cycle)
# - Applied to: hierarchical pin u_udp_stack_top/tx_clk_out_0
# This is the transmit clock generated by the Ethernet IP core
# Used for AXI-Stream interface in transmit direction
create_clock -period 6.400 -name tx_axis_aclk -waveform {0.000 3.200} [get_pins -hierarchical u_udp_stack_top/tx_clk_out_0]



# =============================================================
# 1. External 720 MHz source-synchronous clock (mandatory)
# =============================================================
#create_clock -period 1.389 -name clk_720m -waveform {0.000 0.694} [get_ports clk_720m_p]
create_clock -period 2.778 -name clk_720m -waveform {0.000 1.389} [get_ports clk_720m_p]
# =============================================================
# 2. Generated 90 MHz clock from BUFGCE_DIV (exact instance name in your code)
# =============================================================

# =============================================================
# 3. Regional 720 MHz clock from BUFR (optional but strongly recommended)
# =============================================================
set_property CLOCK_DEDICATED_ROUTE TRUE [get_nets clk_720m]
# =============================================================
# 4. Source-synchronous input delay for data_p/n
#    Conservative values that work reliably on KCU105 + FMC adapter
# =============================================================
set_input_delay -clock clk_720m -max 0.800 [get_ports {data_p data_n}]
set_input_delay -clock clk_720m -min -0.800 [get_ports {data_p data_n}]

# If you ever want to be extra precise with both edges (SDR is single-edge but helps analysis)
# set_input_delay -clock clk_720m -max  0.600 -clock_fall -add_delay [get_ports {data_p data_n}]
# set_input_delay -clock clk_720m -min -0.200 -clock_fall -add_delay [get_ports {data_p data_n}]

# =============================================================
# 5. Asynchronous clock groups (CDC safety)
# =============================================================

# Optional: also cut paths from 720 MHz domain to tx_axis_aclk (never used directly)
set_clock_groups -asynchronous -group [get_clocks clk_720m] -group [get_clocks tx_axis_aclk]

